### PR TITLE
Upgraded Rails to 3.2.21 (latest); Added .ruby-version to .gitignore

### PR DESCRIPTION
**Pull request by jasnow**
Responding to RailsConf request, here is my first pull request.
  * Upgraded Rails to 3.2.21 (latest).
  * Added .ruby-version to .gitignore (I used ruby 2.1.5 because it need less changes).

### CODE REVIEW

**Comment by jasnow** [comment]
Sorry about the 2nd commit. I removed it.

**Comment by jasnow** [comment]
Do I need to do anything else for this PR?

**Comment by presidentbeef** [comment]
Hi Al,

I will need to validate the output of the queries unless you already did that.

**Comment by jasnow** [comment]
ok

**Comment by jasnow** [comment]
Sorry - I did not notice that you did not have many tests. My mistake.

**Pull request closed without merging**
