### PR TITLE
Clean apps

### PR DESCRIPTION
**Pull request by kaiquekandykoga**
Update gemfiles.

Fix 'Clear Results' button in rails 5.
Once this button was clicked, we were unable to run tests.

### CODE REVIEW

**Comment by presidentbeef** [comment]
@kaiquekandykoga Can you rebase onto current master? Maybe that will trigger the CI test. Thanks!

**Comment by kaiquekandykoga** [comment]
Hi @presidentbeef,

I think the CI need to be updated to use different versions of bundler in the apps, but I am not sure how to solve it yet. Can you help me please?

Thank yout a lot.

**Comment by presidentbeef** [comment]
It's working with a single version of Bundler prior to your PR. Can you just undo the change to "Bundled With" in the `Gemfile.lock`?

**Comment by kaiquekandykoga** [comment]
Nice!

It works.

Thank you!!

Happy New Year!!

**Comment by presidentbeef** [comment]
Thank you @kaiquekandykoga!

And I'm very excited that the automated testing and deploying appears to be working 😁

**Pull request merged**
